      
---
# global
sesion: 'Rivarola'
logfile : '/home/pi/'
nchan : 2
nbytes : 2
pkeys : ['aci','bi','ndsi','aei','adi','hs','ht','sc','db']
GSM:
       apn :  '"wap.gprs.unifon.com.ar"'
       url : 'https://script.google.com/macros/s/AKfycbyQX_xnblS1c3M712v-OItr6Se6FcfE19WsiIfW/exec'
       timeout : 180
       offset_file: '/tmp/offset.tmp'  
       queue: '/tmp/queue.tmp'
...
