
---
# global
sesion: 'Rivarola'
logfile : '/home/pi/'
APN :  '"wap.gprs.unifon.com.ar"'
URL : 'https://script.google.com/macros/s/AKfycbyQX_xnblS1c3M712v-OItr6Se6FcfE19WsiIfW/exec'
pkeys : ['aci','bi','ndsi','aei','adi','hs','ht','sc','db']
nchan : 2
nbytes : 2
timeout : 180
offset: 0
queue: ' '
...
